server:
  tomcat:
    threads:
      min-spare: 10
      max: 15
    max-connections: 30
    accept-count: 10
  port: 8080
spring:
  #配置数据源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://175.178.72.68:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
  redis:
    host: 175.178.72.68
    password: Xf123456!
    port: 6379
    database: 9
  cache:
    type: redis